version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wiki
    ports:
      - "3001:3001"
    environment:
      - HOST=0.0.0.0
      - PORT=3001
    restart: always